name: Test the project

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '.github/**'
      - 'README.md'
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Test the project
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test

      - name: Step to run after the test
        run: echo After the test
